#!/bin/bash

scp  ./server.jar 2.2:/home/servisofts/servicios/StaffProUsa/entornos/StaffProUsa/servicios/StaffProUsa/
#scp  ./servicio.pem 2.2:/home/servisofts/servicios/StaffProUsa/entornos/StaffProUsa/servicios/StaffProUsa/
#scp  ./config.json 2.2:/home/servisofts/servicios/StaffProUsa/entornos/StaffProUsa/servicios/StaffProUsa/
#scp  ./servisofts.jks 2.2:/home/servisofts/servicios/StaffProUsa/entornos/StaffProUsa/servicios/StaffProUsa/
# ssh 10 'cd ~/servicios/StaffProUsa/ && ./servisofts.sh down'
# ssh 10 'cd ~/servicios/StaffProUsa/ && ./servisofts.sh up -d'
